server.port=8082

spring.application.name=Retail Billing System

spring.datasource.url=jdbc:mysql://localhost:3306/retailbilling
spring.datasource.username=root
spring.datasource.password=manju
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=manjuswasthik50@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Prevents Jackson from crashing when it finds uninitialized lazy collections or proxies
spring.jackson.serialization.fail-on-empty-beans=false

jwt.secret=VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWNyZXRLZXlGb3JSZXRhaWxCaWxsaW5nU3lzdGVtMjAyNg==
jwt.expiration=86400000
jwt.refresh.expiration=604800000

logging.level.root=INFO
logging.level.com.retailbilling=DEBUG
nvidia.api.key=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
nvidia.api.url=https://integrate.api.nvidia.com/v1/chat/completions